### ISSUE TITLE
Add Tarjan's algorithm

### ISSUE THREAD

**Issue by ZigRazor** [ZigRazor/CXXGraph#103]
**Tarjan's algorithm** for finding strongly connected components in a directed graph
Uses two main attributes of each node to track reachability, the index of that node
within a component(index), and the lowest index reachable from that node(lowlink).
We then perform a dfs of the each component making sure to update these parameters
for each node and saving the nodes we visit on the way.
If ever we find that the lowest reachable node from a current node is equal to the
index of the current node then it must be the root of a strongly connected
component and so we save it and it's equireachable vertices as a strongly
connected component.

**Comment by gaurang7goel** [comment]
HI, i can do this. Can you assign it to me.

**Comment by gaurang7goel** [comment]
@ZigRazor Please assign it someone else, as I was not able to understand the issue properly .

**Comment by ZigRazor** [comment]
ok @gaurang7goel

**Comment by thesmartdeveloperr** [comment]
@ZigRazor i would like to work on this.. pls assign.

**Comment by ZigRazor** [comment]
@thesmartdeveloperr sure! Assigned!

**Comment by ZigRazor** [comment]
@thesmartdeveloperr are you working on it?

**Comment by thesmartdeveloperr** [comment]
no @ZigRazor , please assign it to someone else.

**Comment by suncanghuai** [comment]
@ZigRazor I'd like to work on this, pls assign it to me

**Comment by ZigRazor** [comment]
@suncanghuai sure!
