### ISSUE TITLE
Test_11 Failes if it is not the first time being run

### ISSUE THREAD

**Issue by AlfredCP** [ZigRazor/CXXGraph#118]
Afted building tests, test_11 only passes the first time it is run in a clean build

1. From a clean checkout, follow steps to build tests
2. Run tests with './test_exe'
3. All of them will PASS
4. Run it again
5. Test_11 will fail

Expected test pass always

Suspect that a file is created during a test and it is not clean after the run since it is throwing the following message:
"Value of: exists_test("graph.tsv")
 Actual: true
Expected: false"

**Comment by ZigRazor** [comment]
yes, I saw this issue, after each test the file created should be removed.
Is easy to add this features.
