### ISSUE TITLE
Bug found in RWOutputTest test_22 and test_25 (at least)

### ISSUE THREAD

**Issue by AlfredCP** [ZigRazor/CXXGraph#125]
Those 2 tests supposedly check that compressed files are created (.csv.gz and tsv.gz) and the normal .csv and .tsv are not.
This is checked via ASSERT_FALSE(exists_test(filename)).

If we run test_exe and check the content in the folder, we can see that  .csv and .tsv files have been created, exist in the folder and the test still passes. This is quite scaring because could  be hiding other bugs

1. Build test_exe
2. Run ./test_exe  and it will pass
3. Run ls 
4. Check that supposed non-existing files are there and test still passed.

I would expect both:
- Files are not created
- Test fails if files exist

Test piece of code related to the files - expected results
    ASSERT_FALSE(exists_test("test_25.tsv"));                              --> This file exists and it passes  = INCORRECT
    ASSERT_FALSE(exists_test("test_25_NodeFeat.tsv"));             --> This file exists and it passes  = INCORRECT
    ASSERT_FALSE(exists_test("test_25_EdgeWeight.tsv"));         --> This file exists and it passes  = INCORRECT
    ASSERT_TRUE(exists_test("test_25.tsv.gz"));                          --> This file exists and it passes  = CORRECT
    ASSERT_TRUE(exists_test("test_25_NodeFeat.tsv.gz"));         --> This file exists and it passes  = CORRECT
    ASSERT_TRUE(exists_test("test_25_EdgeWeight.tsv.gz"));      --> This file exists and it passes  = CORRECT

**Comment by ZigRazor** [comment]
Both, but in a future release i want to delete the not compressed one

**Comment by AlfredCP** [comment]
I added the lines to solve this problem.
I consider that all readFromFile functions could be commonalised to reduce the amount of code (for example we are checking the InputOutputFormat many times) but this could be open as an improvement with less priority.
