### ISSUE TITLE
Thread Safe implementations of Boruvka, Prim & Kruskal algorithm

### ISSUE THREAD

**Issue by sidml** [ZigRazor/CXXGraph#128]
This can be nice issue for beginners. 
For reference, existing Thread safe implementations are [here](https://github.com/ZigRazor/CXXGraph/blob/master/include/Graph/Graph_TS.hpp#L343). Similar pattern can be used for adding thread Safe implementations of Boruvka, Prim & Kruskal algorithm.

**Comment by ZigRazor** [comment]
No more applicable, the thread safeness of the functions will be reviewed in a second moment of the project
