### ISSUE TITLE
Range-based for loops to be reviewed

### ISSUE THREAD

**Issue by AlfredCP** [ZigRazor/CXXGraph#153]
**Range-based for loops to be reviewed**
Range-based for loops in several places are used like "for ( auto x : v)". This way they are computing a local copy for every element in the range.
This is a computational useless cost since in some of them we are not even modifying the content of those elements, only reading.

**Possible solution**
Use  "for ( const auto& x : v)"  . In this case we take the elements in the iterable struct as reference (not copying it), and in those places where we don't change the value we can add the "const" keyword to keep safe the structure.

Already commented it in a PR of @sidml

**Comment by AlfredCP** [comment]
@ZigRazor , if you agree, you can assign this to me

**Comment by sidml** [comment]
@AlfredCP 
Thanks for the suggestion. Please let me know if i can help/clarify anything during the modification process.
