### ISSUE TITLE
Use Unordered_map instead of map

### ISSUE THREAD

**Issue by AlfredCP** [ZigRazor/CXXGraph#157]
**In some places in the code, we use std::map and we do not need the sorting functionality of std::map, so we could use unordered_map to get a better performance**

I would suggest to use the unordered_map everywhere when we have a map to link values to a key but we do not need the elements to be ordered according to its key within the map.

**Comment by pavan-pan** [comment]
Hello AlfredCP, is it fine if I can work on it. I am new to this project and this would be something which I think I can do it on my own.

**Comment by AlfredCP** [comment]
Yes of course! I will assign it to you
