### ISSUE TITLE
Sometimes BellmanFordTest.test_5 fails

### ISSUE THREAD

**Issue by AlfredCP** [ZigRazor/CXXGraph#158]
**BellmanFordTest.test_5 fails but not always**

Steps to reproduce:
- Run tests several times, and som of them it fails under error:

```
BellmanFordTest.cpp:170: Failure
Value of: res.negativeCycle
  Actual: true
Expected: false
```

**Comment by AlfredCP** [comment]
Same happens randomly for FWTest   test_3

`FWTest.cpp:113: Failure
Value of: res.negativeCycle
  Actual: true
Expected: false
[  FAILED  ] FWTest.test_3 (0 ms)`

**Comment by sidml** [comment]
That's weird.. I ran a few times and didn't get this error. Did you make any changes to the code ?
@ZigRazor Do you get this error ?

**Comment by AlfredCP** [comment]
It is really weird, is it multithreading? maybe somehow I am stressing the processes and starts to get crazy.
I  am running it in a virtual machine... 

I just took a fresh clone from https://github.com/ZigRazor/CXXGraph.git  and it happens as well.
Don't know what to think hahaha

**Comment by AlfredCP** [comment]
I suspect about this:
https://stackoverflow.com/questions/3845353/what-will-be-the-default-value-of-an-uninitialized-boolean-value-in-c/3845383

I am trying to initialize to false and will see if I can make it fail

**Comment by AlfredCP** [comment]
Ok, I think this is indeed the problem, after initializing those bool values which were not set during the algorithm, I could run it 15 times in a row without any Fail.
I think this is a small problem compared to what could happen.

I propose to creat a ticket to add initial values to all structures, at least to the ones that does not have default value, something like '0's and false.

**Comment by ZigRazor** [comment]
> Ok, I think this is indeed the problem, after initializing those bool values which were not set during the algorithm, I could run it 15 times in a row without any Fail. I think this is a small problem compared to what could happen.
> 
> I propose to creat a ticket to add initial values to all structures, at least to the ones that does not have default value, something like '0's and false.

I Agree with you!
