### ISSUE TITLE
Refactoring: writeToStandardFile_tsv and writeToStandardFile_csv

### ISSUE THREAD

**Issue by pavan-pan** [ZigRazor/CXXGraph#168]
The methods writeToStandardFile_tsv and  writeToStandardFile_csv in Graph.hpp have duplicate code. Moving the duplicate code to a common method makes it easier to make future changes. Similar issue with readFromStandardFile_tsv and readFromStandardFile_csv.

**Comment by sidml** [comment]
@pavan-pan Let me know if you want to work on this. I will assign it to you.

**Comment by pavan-pan** [comment]
@sidml yes please. Thank you.

**Comment by ZigRazor** [comment]
@pavan-pan if you demostrate interest in this project I elect you collaborator, just 1 or 2 more good Pull Request!

**Comment by pavan-pan** [comment]
@ZigRazor that would be great!
