### ISSUE TITLE
Dijkstra can not work with DirectedWeightedEdge

### ISSUE THREAD

**Issue by aengusjiang** [ZigRazor/CXXGraph#205]
Not init for some node dist in Graph.hpp:1007~1009

Please make sure the right iterate container.
It is better that replace as below:
		for (const auto &elem : nodeSet )
		{
			dist[elem.first] = INF_DOUBLE;
		}

**Comment by ZigRazor** [comment]
Good Observation!
Thank you so much.
If you have pleasure to solve this, you can contribute to this project. :)

**Comment by ZigRazor** [comment]
Corrected in #206
