### ISSUE TITLE
Add Disjoint Union Algorithm

### ISSUE THREAD

**Issue by ZigRazor** [ZigRazor/CXXGraph#215]
Implementation of [Disjoint union](https://en.wikipedia.org/wiki/Disjoint_union) algorithm to find connected components in graph efficently.

**Comment by harshraj438524** [comment]
hi @ZigRazor i would love to solve this problem...will you provide this to me?

**Comment by ZigRazor** [comment]
Yes, I assign it to you @harshraj438524 !

**Comment by ZigRazor** [comment]
@harshraj438524 are you working on it?

**Comment by ZigRazor** [comment]
Deassigned due to inactivity

**Comment by Happylinzy** [comment]
I would like to take this request. If I understand it correctly, the algorithm is to implement a union-find algorithm on the graph in Graph.cpp

**Comment by ZigRazor** [comment]
Yes, I will assign it to you

**Comment by Happylinzy** [comment]
What is the expected output of union find algorithm?

Here is what I think:
If we want to decide if two nodes are in the same connected components, we could maintain a union find data structure while construcing the graph. Then when the function for example isInSameConnectedComponent called, it directly checks the stored map to get the result.

Then the the modification to the union find map is enbedded into add edge, delete edge method.

**Comment by Happylinzy** [comment]
In addition, I found that functions used for union find have been implemented as setFind, setUnion in Graph.hpp :).

**Comment by ZigRazor** [comment]
Ok, so we can close this issue?

**Comment by Happylinzy** [comment]
Yes. I think we can close it.
