### ISSUE TITLE
Add Description in README for Kosaraju Algorithm

### ISSUE THREAD

**Issue by ZigRazor** [ZigRazor/CXXGraph#225]
Please Add the description in Readme for Kosaraju Algorithm

**Comment by pratiksrivastava01** [comment]
@ZigRazor please assign this to me

**Comment by Adw8** [comment]
Hi @ZigRazor, I would like to work on this issue, can you assign it to me?

**Comment by ZigRazor** [comment]
Sure! @Adw8
