### ISSUE TITLE
Introduction of Kahn's Algorithm for topological sort

### ISSUE THREAD

**Issue by ZigRazor** [ZigRazor/CXXGraph#237]
please introduce Kahn's Algorithm for topological sort

**Comment by poorvaditya18** [comment]
Hey, I'm interested in solving this issue. Can I work on that?

**Comment by ZigRazor** [comment]
Sure! I assign it to you @poorvaditya18

**Comment by ZigRazor** [comment]
Hi @poorvaditya18 

No, you should implement the algorithm in the Graph.hpp template class, as other algorithm are implemented.

**Comment by ZigRazor** [comment]
@poorvaditya18  are you working on it?

**Comment by pradkrish** [comment]
is this issue still open? I am happy to work on this.

**Comment by ZigRazor** [comment]
Yes, is still open, due to inactivity of @poorvaditya18 I will assign it to you @pradkrish
