### ISSUE TITLE
Add The best First Search algorithm

### ISSUE THREAD

**Issue by ZigRazor** [ZigRazor/CXXGraph#239]
Please add The best First Search algorithm for finding the shortest path from a given starting node to a goal node in a graph.

**Comment by yogesh-9999** [comment]
Hey @ZigRazor  assign me this issue

**Comment by ZigRazor** [comment]
Sure!

**Comment by ZigRazor** [comment]
Deassigned due to inactivity

**Comment by pradkrish** [comment]
Hello, is this issue available? I wouldn't mind giving it a go. I am currently thinking about a function signature like the following

```
template <typename T>
const std::vector<Node<T>> Graph<T>::best_first_search(const Node<T> &source, const Node<T> &target) 
```
based on the implementation [here](https://www.geeksforgeeks.org/best-first-search-informed-search/). do you think this approach is okay?

**Comment by ZigRazor** [comment]
Yes, it's available.

I assign it to you.
The signature is good, and also the implementation link.
You can proceed with the implementation
