### ISSUE TITLE
Return Type of Kosaraju Proposal

### ISSUE THREAD

**Issue by ZigRazor** [ZigRazor/CXXGraph#261]
I'm still not completely convinced about the return type though. Specifically:
- Wouldn't it be better if the returned connected components contained pointers to the vertex in the graph, instead of (subgraph) copies? I mean, if one wants to check which component a given vertex of the graph belongs to, I think it would make more sense to refer to vertices in the original graph than to vertices in a graph isomorphic/identical to the original. But this question applies to other algorithms in the library too (e.g. BFS, DFS). In some cases (e.g. Max flow, MST algorithms) we return vectors of pairs of strings for the edges, why don't we return vectors of pointers to edges instead? I general, I feel that the interface is a bit too heterogeneous concerning algorithms returns type.

- With this choice of data structure (i.e. std::vector) it is kind of hard to get the strongly connected component for a given vertex (linear time search). Maybe doing something like what has been done for DialResult (i.e. unordered_map) could simplify this. And providing hashing for single vertices is not really a problem since they already have an id attribute.

_Originally posted by @dvd2000 in https://github.com/ZigRazor/CXXGraph/issues/260#issuecomment-1424249585_

**Comment by guru2396** [comment]
Hello. The new return type of this algorithm should be the one suggested as below??

I took a look at the approach used in the Boost graph library and they are using a map with vertices as keys and distinct labels for every strongly connected component as values. We can maybe do something similar here? But I think it would be important to keep consistency with the rest of the library.

Originally posted by @dvd2000 in #251

**Comment by ZigRazor** [comment]
Yes, we can do something similar in this library

**Comment by guru2396** [comment]
okay. Can I take this up?

**Comment by ZigRazor** [comment]
sure

**Comment by guru2396** [comment]
@ZigRazor, one more thing that can be modified. I think the adjacency matrix can be used to populate the nodeSet in getNodeSet() method instead of using edgeSet. This method is used many times in the code, so may be there can be some benefit.

**Comment by ZigRazor** [comment]
> @ZigRazor, one more thing that can be modified. I think the adjacency matrix can be used to populate the nodeSet in getNodeSet() method instead of using edgeSet. This method is used many times in the code, so may be there can be some benefit.

Yes @guru2396 but open a new issue for this improvement

**Comment by guru2396** [comment]
okay sure, will open
