### ISSUE TITLE
Why have you put this on Haxelib?

### ISSUE THREAD

**Issue by nanjizal** [ZigRazor/CXXGraph#271]
Please clarify why you have added this as a haxelib?  

Haxelib is designed for the Haxe language ecosystem, it is not possible to use your library from Haxe in it's current form ( without any bindings/externs ).

I would expect any haxelib to have some haxe use example or explanation of use, otherwise surely it is spam and misuse of Haxelib?  Haxe is a small programming community and so, I feel it is not good form to spam it's repository with an unrelated library. 

Obviously the community would be very happy if you write some haxe c++ externals and provide basic example use, but otherwise your library should be removed from haxelib.  

Note you can use haxelib.json to install a git repo without needing to put it on the official haxelib, and this would be the recommended approach for any library that is not yet setup for Haxe language users, so you don't need to upload to haxelib for just convenience, just have haxelib.json in your git repo.

The haxe language developers mostly adopt more permissive licences like MIT and Apache2, so AGPL v3.0 is not really going to interest many.  Please clarify as soon as possible as your library in it's current form is not really suitable for haxelib repository.

**Comment by nanjizal** [comment]
perhaps you could use this to help with adding externs.
https://lib.haxe.org/p/wrapgen/

**Comment by ZigRazor** [comment]
Sorry, I missundestood the use of Haxelib.

can you tell me how to remove the library from repo? 

Thank you so much!

**Comment by nanjizal** [comment]
No worries prob check with Andy Li on twitter, it maybe quite easy for you to add externs to allow haxe use and makes it easy to use your library within say a Flixel mobile game. I believe Ammer is the current approach to creating externs for c++.

**Comment by ZigRazor** [comment]
Sorry @nanjizal, but I want to remove the library from Haxelib.
Do you know what is the command?

**Comment by tobil4sk** [comment]
@ZigRazor There is no command currently, to get it removed you'll have to talk to Andy Li (either on twitter or by opening an issue here):
https://github.com/HaxeFoundation/haxelib/issues

**Comment by ZigRazor** [comment]
Thank you I removed it!
