### ISSUE TITLE
Make CXXGraph MSVC-Compatible

### ISSUE THREAD

**Issue by nrkramer** [ZigRazor/CXXGraph#277]
Currently, the library relies on some Unix stdlib functionality (namely, `rand_r`)

To make the library more portable, alternative functions and C++ functionality should be added to make sure MSVC users can compile. This will go a long way to ensuring portability as well.

We can start by replacing `rand_r` with a PRNG from `<random>`

**Comment by nrkramer** [comment]
I'll open a PR for this once https://github.com/ZigRazor/CXXGraph/pull/276 is merged

**Comment by ZigRazor** [comment]
ok #276 is merged

**Comment by nrkramer** [comment]
Opened https://github.com/ZigRazor/CXXGraph/pull/280
