### ISSUE TITLE
All namespaces should be titlecase

### ISSUE THREAD

**Issue by nrkramer** [ZigRazor/CXXGraph#278]
The Namespace for the library should match the name you've got here on Github

**Comment by nrkramer** [comment]
Additionally, all the other namespaces should use title-case as well (such as PARTITIONING -> Partitioning)

**Comment by ZigRazor** [comment]
Yes, I agree with your observation!

**Comment by nrkramer** [comment]
This is done with https://github.com/ZigRazor/CXXGraph/pull/281
