### ISSUE TITLE
Add convenience functions for computing out neighbor nodes, inout neighbor nodes

### ISSUE THREAD

**Issue by nrkramer** [ZigRazor/CXXGraph#310]
While almost all graph searching and neighbor lookups can be accomplished through the adjacency matrix, it is sometimes very useful for programmers to iteravely go through neighbors by providing a pointer to a node.

This can be done by simply using the adjacency matrix and determining the edge type, then returning the set of edges that satisfies the direction.

Formally, this feature request is to provide functions such as `outEdges(Node<T>* node)` and `inOutEdges(Node<T>* node)`, which will return out edges from a node in a directed graph and all edges from a node in any graph, respectively.

**Comment by sbaldu** [comment]
Hey @nrkramer, is this what you had in mind?
```
template <typename T>
const std::set<const Node<T> *> Graph<T>::outEdges(const Node<T> *node) const {
  auto adj = getAdjMatrix();
  if (adj->find(node) == adj->end()) {
	return std::set<const Node<T> *>();
  }
  auto nodeEdgePairs = adj->at(node);

  std::set<const Node<T> *> outEdges;
  for (auto pair : nodeEdgePairs) {
	if (pair.second->isDirected().has_value() && pair.second->isDirected().value()) {
	  outEdges.insert(pair.first);
	}
  }

  return outEdges;
}

template <typename T>
const std::set<const Node<T> *> Graph<T>::inOutEdges(const Node<T> *node) const {
  auto adj = Graph<T>::getAdjMatrix();
  if (adj->find(node) == adj->end()) {
	return std::set<const Node<T> *>();
  }
  auto nodeEdgePairs = adj->at(node);
  
  std::set<const Node<T> *> inOutEdges;
  for (auto pair : nodeEdgePairs) {
	inOutEdges.insert(pair.first);
  }
  
  return inOutEdges;
}
```

**Comment by nrkramer** [comment]
I think there's convenience in both cases - however with just the set of nodes it's trivial to reconstruct the edges.

A separate issue can be filed to address the edges case. I'll rename this issue to address getting the nodes.

**Comment by ZigRazor** [comment]
Perfect
