### ISSUE TITLE
Path for djisktra

### ISSUE THREAD

**Issue by LumiereDeLOmbre** [ZigRazor/CXXGraph#331]
Thanks for your lib.

It would be nice to have the nodes in order that make the shortest path, not only the resulting distance.

:+1:

**Comment by ZigRazor** [comment]
Nice Request!

**Comment by Happylinzy** [comment]
I would like to contribute to this request.

**Comment by ZigRazor** [comment]
Ok, I assign this to you!

**Comment by guru2396** [comment]
Hello, I have forked this repo and did the necessary changes. Can I still contribute to this request?

**Comment by Happylinzy** [comment]
> Hello, I have forked this repo and did the necessary changes. Can I still contribute to this request?

You can get it. @ZigRazor . Please assign it to @guru2396 .

**Comment by ZigRazor** [comment]
Assigned by @sbaldu to @guru2396
