### ISSUE TITLE
Edge equality operator is incorrect

### ISSUE THREAD

**Issue by nrkramer** [ZigRazor/CXXGraph#333]
The current edge equality operator is this:
```
template <typename T>
bool operator==(shared<const Edge<T>> p1, shared<const Edge<T>> p2) {
  return p1->getNodePair().first->getUserId() ==
             p2->getNodePair().first->getUserId() &&
         p2->getNodePair().second->getUserId() ==       <<<< bad
             p2->getNodePair().second->getUserId();
}
```

This is incorrect, since the second user ids are not getting compared against each-other (we're comparing `p2->getNodePair().second->getUserId()` against itself).

This will be changed to:
```
template <typename T>
bool operator==(shared<const Edge<T>> p1, shared<const Edge<T>> p2) {
  return p1->getNodePair().first->getUserId() ==
             p2->getNodePair().first->getUserId() &&
         p1->getNodePair().second->getUserId() ==       <<<< good
             p2->getNodePair().second->getUserId();
}
```

To resolve this bug.

Edge equality is a core functionality of this library. Therefore I'm marking this as critical.

**Comment by sbaldu** [comment]
Yep, it's a typo, my bad. Thanks : )

**Comment by nrkramer** [comment]
Opened a PR here: https://github.com/ZigRazor/CXXGraph/pull/326
