### ISSUE TITLE
Inconsistent `id` types

### ISSUE THREAD

**Issue by nrkramer** [ZigRazor/CXXGraph#338]
There are sections of code where we use `unsigned long` for `id`s, some where we use `std::size_t`, and some we use `unsigned long long`. For example:

### Node.hpp
https://github.com/ZigRazor/CXXGraph/blob/7c03e1a5a69cd9ad6f141e1cd0efe08ce279ff63/include/Node/Node.hpp#L36

Here we're declaring `std::size_t id = 0`

### Edge.hpp
https://github.com/ZigRazor/CXXGraph/blob/7c03e1a5a69cd9ad6f141e1cd0efe08ce279ff63/include/Edge/Edge.hpp#L49

Here we're declaring `unsigned long long id = 0;`

### DirectedEdge.hpp
https://github.com/ZigRazor/CXXGraph/blob/7c03e1a5a69cd9ad6f141e1cd0efe08ce279ff63/include/Edge/DirectedEdge.hpp#L48

Here we declare a constructor using `const unsigned long id`

## Discussion

We should probably land on a concrete type that's declared in `namespace CXXGraph` and used universally throughout the library for id types.

Generally, I think 64 bits is more than enough for most use-cases, with a good tradeoff with performance/reduced hash collision when comparing ids. Lower bit values could squeeze out more performance - but it's highly use-case dependent.

Perhaps wherever we declare the id type, we should give the user the chance to redefine the type so that smaller or larger bit values can be used across the library. Perhaps with a documented macro.

What are your thoughts @sbaldu @ZigRazor ?

**Comment by ZigRazor** [comment]
I Agree with you solution!

**Comment by nrkramer** [comment]
Another alternative would be to completely overhaul the current `id` system with a hash-based approach that mirrors what STL does in classes such as `std::set` or `std::unordered_map`.

**Comment by sbaldu** [comment]
I agree as well

**Comment by nrkramer** [comment]
Alright, I'll take this one then
