### ISSUE TITLE
Bellman–Ford Algorithm

### ISSUE THREAD

**Issue by ZigRazor** [ZigRazor/CXXGraph#34]
Implementation of Bellman–Ford Algorithm

**Comment by arunim-iiitlCS** [comment]
can i contribute to this problem, please do assign me. @ZigRazor

**Comment by ZigRazor** [comment]
Obviously, i assign it to you!

**Comment by sidml** [comment]
@ZigRazor 
I wanted to work on Bellman-Ford. Before starting, I wanted to clarify something.
While going through the [Dijsktra implementation](https://github.com/ZigRazor/CXXGraph/blob/8b6e56b6ceb5a177ce7298edcca36d03e440c937/packaging/deb/CXXGraph/usr/include/Graph.hpp#L1266), I got the impression that in the Bellman–Ford algorithm we just need to add additional checks for negative-weight cycle and return null error if graph contains negative weight cycle.
What do you think ?

**Comment by ZigRazor** [comment]
> What do you think ?

I think is correct.

I assign this issue to you @sidml
