### ISSUE TITLE
Faster edge lookup

### ISSUE THREAD

**Issue by nrkramer** [ZigRazor/CXXGraph#340]
Edge lookup is currently done by iterating over all edges:
```
template <typename T>
bool Graph<T>::findEdge(shared<const Node<T>> v1, shared<const Node<T>> v2,
                        unsigned long long &id) const {
  // This could be made faster by looking for the edge hash, assuming we hash
  // based on node data, instead of a unique integer
  for (auto e : this->edgeSet) {
    if ((e->getNodePair().first == v1) && (e->getNodePair().second == v2)) {
      id = e->getId();
      return true;
    }
    if (!e->isDirected() &&
        ((e->getNodePair().second == v1) && (e->getNodePair().first == v2))) {
      id = e->getId();
      return true;
    }
  }

  id = 0;
  return false;
}
```

This could probably be made a lot faster if we relied on two changes:
1. Cache and update the Adjacency Matrix whenever a node or edge is added/removed/changed
2. Utilize the cached Adjacency Matrix for all node and edge searches, using the superior hash lookup speed when the search space is larger

Or alternatively, we store a lookup table of edges with bucketing for repeat edges.

**Comment by sbaldu** [comment]
I agree with your solution. Caching seems perfect

**Comment by ZigRazor** [comment]
Yes, I agree with you cache solution!

**Comment by guru2396** [comment]
Hello. Can I give this a try?

**Comment by ZigRazor** [comment]
Yes, I assign it to you

**Comment by guru2396** [comment]
Hi, I am facing an issue. The "test_exe.exe" is not running all the tests. Below is the output
Running Test for CXXGraph Version 2.0.0
[==========] Running 246 tests from 33 test suites.
[----------] Global test environment set-up.
[----------] 4 tests from UnionFindTest
[ RUN      ] UnionFindTest.setFindTest1

The execution ends after this.

**Comment by ZigRazor** [comment]
Do you have a core?

**Comment by guru2396** [comment]
Sorry I didn't get you. Can you please elaborate

**Comment by ZigRazor** [comment]
When you start the test_exe the application crash? Generate a coredump? 
Can you please start the application in debug? ( if possible with GDB )
