### ISSUE TITLE
Add `CXXGraph::Node` storage to `CXXGraph::Graph` to support trivial graphs and friends

### ISSUE THREAD

**Issue by nrkramer** [ZigRazor/CXXGraph#341]
There are use-cases where someone may want to add a node to the graph without edges.

The use-cases:
- Trivial graph  ["Introduction to Graph Theory", Douglas B. West]. Graph with no edges
- Non-trivial graphs with isolated nodes

**Comment by nrkramer** [comment]
@ZigRazor Would you mind finding someone else to work on this one? I have enough on my plate right now

**Comment by ZigRazor** [comment]
Good new feature.
I think someone can take this I pin it!

**Comment by sbaldu** [comment]
I can take this one

**Comment by sbaldu** [comment]
@ZigRazor @nrkramer So now the nodeSet becomes a member of the graph class, and when we create edges we also add the corresponding nodes to the nodeSet. Correct?

**Comment by ZigRazor** [comment]
We need to try to minimize the overhead, or the max number of edge in the graph will be ever smaller.

**Comment by nrkramer** [comment]
> So now the nodeSet becomes a member of the graph class, and when we create edges we also add the corresponding nodes to the nodeSet. Correct?

Yes, that seems like a reasonable solution.

**Comment by sbaldu** [comment]
> > So now the nodeSet becomes a member of the graph class, and when we create edges we also add the corresponding nodes to the nodeSet. Correct?
> 
> Yes, that seems like a reasonable solution.

The PR is almost ready, but I was thinking, do you think that it would be better to keep the nodeSet as it was before, and implement a nodeSet member that only contains isolated nodes, which we'd add with `addNode`? And when we use `getNodeSet` we just merge the usual nodeSet with the isolated nodes.
In this way we would allow the use of isolated nodes without slowing down the code.

**Comment by ZigRazor** [comment]
This could be a valuable possibility, for me it's the best solution. What do you think @nrkramer ?

**Comment by sbaldu** [comment]
> This could be a valuable possibility, for me it's the best solution. What do you think @nrkramer ?

Ok, I'll rewrite it in this way then. Thanks

**Comment by nrkramer** [comment]
As a follow-up, since the PR was merged, I think this is a good addition. Thanks for working on this @sbaldu
