### ISSUE TITLE
addEdge() method does not copy the weight 

### ISSUE THREAD

**Issue by fajlip** [ZigRazor/CXXGraph#350]
**Describe the bug**
Graph.addEdge() method calls a wrong constructor; thus if you give it undirectedWeightedEdge, it does not copy its weight; leading to unpredictable algorithms results. I imagine similar problem is with directedWeighted edge, but I have not tried it.

**To Reproduce**
CXXGraph::Node<int> a("a",0);
CXXGraph::Node<int> b("b",0);
CXXGraph::UndirectedWeightedEdge<int> edge(0, a, b, 3.3);
graph.addEdge(&edge);

**Expected behavior**
I expect that the edge gets added to the graph with the weight equal 3.3

**Additional context**
Temporary fix:
````cpp
template <typename T>
void Graph<T>::addEdge(const Edge<T> *edge) {
  if (edge->isDirected().has_value() && edge->isDirected().value()) {
    if (edge->isWeighted().has_value() && edge->isWeighted().value()) {
      auto edge_shared = make_shared<DirectedWeightedEdge<T>>(*edge);
      this->edgeSet.insert(edge_shared);
    } else {
      auto edge_shared = make_shared<DirectedEdge<T>>(*edge);
      this->edgeSet.insert(edge_shared);
    }
  } else {
    if (edge->isWeighted().has_value() && edge->isWeighted().value()) {
      auto edge_shared = make_shared<UndirectedWeightedEdge<T>>(*edge,
          dynamic_cast<const UndirectedWeightedEdge<T>&>(*edge).getWeight());
      this->edgeSet.insert(edge_shared);
    } else {
      auto edge_shared = make_shared<UndirectedEdge<T>>(*edge);
      this->edgeSet.insert(edge_shared);
    }
  }
}
````

**Comment by sbaldu** [comment]
@fajlip Are you opening a PR?

**Comment by fajlip** [comment]
@sbaldu It is just a proposed solution; maybe there are better ones, maybe it affects something else. I would rather let author to decide how to deal with the situation with his complete knowledge of library.

**Comment by ZigRazor** [comment]
I think you solution is good

**Comment by fajlip** [comment]
Thank you for your fix!

**Comment by arcturusannamalai** [comment]
I wonder why value() from the optional is being gated ? Is it because it’s a pointer ?

**Comment by ZigRazor** [comment]
> I wonder why value() from the optional is being gated ? Is it because it’s a pointer ?

@arcturusannamalai  the value() is being gated because it should be not set. It's ever better to check it.
