### ISSUE TITLE
Use of cached adjacency matrix in all algorithms

### ISSUE THREAD

**Issue by sbaldu** [ZigRazor/CXXGraph#356]
Since we now have a `cachedAdjacencyMatrix` member, wouldn't it be better to use it in all the algorithms, instead of calling the `getAdjMatrix` method? I think that in some applications this would save a lot of time, especially for very large graphs.

**Comment by nrkramer** [comment]
It absolutely would. I encourage we replace all usages with utilized the cached adj matrix.
