### ISSUE TITLE
Implement matrices used in network dynamics

### ISSUE THREAD

**Issue by sbaldu** [ZigRazor/CXXGraph#359]
Related to issue #107, which concerns the Markov-Chain algorithm, I think that it would be useful to provide getters for the matrices most widely used in the study of network dinamics, like the degree matrix, the laplacian matrix, transition or stochastic matrix, ecc.
I leave down here some reference:
* degree: https://en.wikipedia.org/wiki/Degree_matrix
* laplacian: https://en.wikipedia.org/wiki/Laplacian_matrix
* transition/stochastic: https://en.wikipedia.org/wiki/Stochastic_matrix

**Comment by carlosfrodrigues** [comment]
Hi, I would like to take this one. Could you assign for me?

**Comment by ZigRazor** [comment]
yes @carlosfrodrigues
