### ISSUE TITLE
Add generic `addNode` and `addEdge` overloads

### ISSUE THREAD

**Issue by sbaldu** [ZigRazor/CXXGraph#361]
I was thinking that it might be nice to add overloads for the `addNode` and `addEdge` methods that take an arbitrary number of nodes or edges.  
This could be done with something like:
```
template <typename T1, typename... Tn>
void Graph<T>::addNode(T1 node, Tn... nodes) {
```
and in addition it would be nice to define a type trait that makes sure that the template parameter is in fact a node/edge, like:
```
template <typename T>
struct is_node : std::false_type {};

template <typename T>
struct is_node<const Node<T>*> : std::true_type {};
```
so that the complete function declaration becomes:
```
template <typename T1, typename... Tn>
requires is_node<T1>::value && (is_node<Tn>::value && ...)
void Graph<T>::addNode(T1 node, Tn... nodes) {
```
This might be an overkill but I think that it could be a useful addition;
What do you think @ZigRazor @nrkramer?

P.S. the use of `requires` needs C++20, but considering issue #266 I suppose that there was already the intention of updating the standard version.

**Comment by nrkramer** [comment]
I don't think forcing users to upgrade their version of the C++ standard is necessarily a good thing.

Supporting new features from the standard is fine as long as it's hidden in the library - but if it's in the headers it becomes a far more troublesome problem.

Having the maximum amount of backwards compatibility is a _good_ thing. Most library implementers should strive for that.


This being said, the template variadic list is a neat idea.

**Comment by nrkramer** [comment]
I think we should discuss and consider the possibility of distributing a standard hpp/cpp library, as the drawbacks of header-only are starting to manifest in this library.

**Comment by nrkramer** [comment]
This SO article goes over some of the basic points: https://softwareengineering.stackexchange.com/questions/305618/are-header-only-libraries-more-efficient

I do think the low administrative costs of a header-only library make it attractive to keep.

**Comment by ZigRazor** [comment]
> I think we should discuss and consider the possibility of distributing a standard hpp/cpp library, as the drawbacks of header-only are starting to manifest in this library.

I think we can open a discussion in discussion section.

**Comment by ZigRazor** [comment]
> I do think the low administrative costs of a header-only library make it attractive to keep.

I Agree with @nrkramer

**Comment by sbaldu** [comment]
> This being said, the template variadic list is a neat idea.
If you think that it would be a useful addition we could still implement the new method without using the C++20 `requires`.  
I think that we can implement the check on the template parameters by simply using `std::enable_if`, which is from C++11 so we don't need to update the standard.  
What do you think?

**Comment by ZigRazor** [comment]
In this way, I think is good!

**Comment by sbaldu** [comment]
Great!
