### ISSUE TITLE
Break out algorithms in Graph.hpp into Algorithms/ folder

### ISSUE THREAD

**Issue by nrkramer** [ZigRazor/CXXGraph#364]
Graph.hpp has become pretty large and is a bit of a pain to sift through.

We should break-out Graph.hpp into two major modules:
1. Graph.hpp will contain the declaration of `class Graph` and define basic construction elements, edge, and node operations.
2. Graph/Algorithms/... will contain algorithm implementations that implement the algorithms declared in Graph.hpp.

If we want to remove the need for users to include algorithm files, we can create `Graph_decl.hpp` as a pure declaration file for `class Graph`, and have implementations in `Graph.hpp` and Algorithms/.... Tbh not entirely sure this is necessary, but it might avoid a circular include.

We can also use this as an opportunity to move some of the utility functions, such as reading and writing to various file formats, into Utils/Graph/... subfolder.

**Comment by nrkramer** [comment]
I can take this work

**Comment by ZigRazor** [comment]
Yes, I think is a good idea.
You can work on this!
