### ISSUE TITLE
Build a Docusaurus Documentation

### ISSUE THREAD

**Issue by ZigRazor** [ZigRazor/CXXGraph#384]
Please add Documentation Site built with Docusaurus.
This issue can be releated to #213 .

**Comment by Horicabu** [comment]
Hello, I'd be happy to take a swing at this.

**Comment by ZigRazor** [comment]
Ok, I assign it to you @Horicabu

**Comment by Horicabu** [comment]
Hello Zigrazor, I've finally got some proper time to work on this project, and I am in early stages of configuration and preparing to port over your docs.

While I'm here, do you have any site elements you'd like carried over from your Pages site?

**Comment by ZigRazor** [comment]
Not at the moment, after a first deploy we can discuss how to integrate all the elements necessary.
Obviously, the minimum requirement are an introduction to the framework, some documentation and contacts

**Comment by Horicabu** [comment]
Sounds good. expect an early build soon.

**Comment by Horicabu** [comment]
Hello Zigrazor! Apologies for the long wait, but I have an early build with the gh-pages documentation alongside previously discussed features ready to deploy.

How do you want to deploy the site for initial review?

**Comment by ZigRazor** [comment]
I think you can release it as a pull request on _gh-pages_  branch. Then you can help me to deploy it on github pages

**Comment by Horicabu** [comment]
https://github.com/ZigRazor/CXXGraph/pull/402.
I imagine fat will need to be trimmed from this PR. Do advise.

**Comment by ZigRazor** [comment]
The base site is up, for modify the Site the branch is `WebSite`.
Just push the changed files and the site will be updated.
Thank you for first implementation to @Horicabu.
If you want to continue contribute to the website you are welcome!
