### ISSUE TITLE
[BUG] Illegal Instruction SIGILL in addEgdes_1

### ISSUE THREAD

**Issue by ZigRazor** [ZigRazor/CXXGraph#386]
I have the following signal ( SIGILL ) when the test `addEgdes_1` is executed.
![Error1](https://github.com/ZigRazor/CXXGraph/assets/16266721/d79ce239-205e-43cb-8a88-3c42b14a11e7)

![stackTrace](https://github.com/ZigRazor/CXXGraph/assets/16266721/19f77d7b-6e3f-435c-96b7-34b17e5abf14)

The platform is codespace with the following tools:
- cmake version 3.16.3
- g++ (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0

**Comment by sbaldu** [comment]
I'll fix it asap

**Comment by ZigRazor** [comment]
Closed by #389
