### ISSUE TITLE
Add a Native Getting Started Guide

### ISSUE THREAD

**Issue by Horicabu** [ZigRazor/CXXGraph#407]
CXXGraph lacks a proper getting started guide in its native documentation, despite comparable guides existing [elsewhere on the web](https://dev.to/cxxgraph/revolutionizing-data-processing-with-cxxgraph-a-comprehensive-guide-to-graph-data-structures-in-c-3od5).

I would like to contribute a getting started guide for the native documentation.

**Comment by ZigRazor** [comment]
Good! you can start in a separate README or directly in the new website with docusaurus!

**Comment by Horicabu** [comment]
A quick question regarding the [installation guide](https://zigrazor.github.io/CXXGraph/getting-started/installation).

I cannot seem to get the unix commands to function (I am using MacOS Monterey, for reference). I believe the problem is ambigious syntax in the command template.

> $ sudo tar xjf CXXGraph-{version}.tar.bz2
I'm 70% sure there is a specific way one fills in {version} that I am missing.

**Comment by ZigRazor** [comment]
@Horicabu  you should replace `{version}` with the release version

**Comment by Horicabu** [comment]
I gathered as much, but what is the syntax for the command? Perhaps this is a silly question, however I am clearly missing some information.
![Screen Shot 2024-04-15 at 2 35 44 PM](https://github.com/ZigRazor/CXXGraph/assets/53095360/2aa43300-e38e-4342-a6f7-e151f8e29d12)

**Comment by ZigRazor** [comment]
Do you have create the tarball before? 

To create a tarball package, execute the following from the command line:

```
# Enter Packaging Directory
$ cd packaging
# Execute the script to generate tarballs
$ ./tarballs.sh
```

**Comment by Horicabu** [comment]
Is the installation guide as provided not a way to download a release version of the project? On my last project, a similar command was used to download a compressed archive (.tar file) from the devs, not the other way around.

I thought packaging was a method to export your own builds using CXXGraph? That would be the opposite to what I am trying to do.

**Comment by ZigRazor** [comment]
should be inserted in the release assets all the compiled package. this could be solution, we can try to add this to the CI/CD workflow
