### ISSUE TITLE
Windows builds are broken due to MSVC fold expression bug

### ISSUE THREAD

**Issue by nolankramer** [ZigRazor/CXXGraph#415]
**Describe the bug**

MSVC has notoriously been bad at compiling valid C++ with variadic template expansions and fold expressions.

The code we currently use to enable template expansion for adding multiple nodes or edges causes MSVC to choke:
```
std::enable_if_t<is_node_ptr_v<T1> && (is_node_ptr_v<Tn> && ...), void>
std::enable_if_t<is_edge_ptr_v<T1> && (is_edge_ptr_v<Tn> && ...), void>
```

To work around this, we'll need to add a patch that breaks-out the template expansion into its own type trait.

**Comment by nolankramer** [comment]
FYI @ZigRazor , this is my second GitHub profile (I'm @nrkramer )

**Comment by nolankramer** [comment]
I've opened https://github.com/ZigRazor/CXXGraph/pull/416

**Comment by ZigRazor** [comment]
> FYI @ZigRazor , this is my second GitHub profile (I'm @nrkramer )

Tomorrow I will add you as collaborator!
