### ISSUE TITLE
Graph<T>::removeNode has potential to throw due to optional being accessed early

### ISSUE THREAD

**Issue by nolankramer** [ZigRazor/CXXGraph#418]
The implementation that added isolated nodes seems to be assuming that `nodeOpt` will always have a value. This is untrue if the node does not exist:
```
template <typename T>
void Graph<T>::removeNode(const std::string &nodeUserId) {
  auto nodeOpt = getNode(nodeUserId);
  auto isolatedNodeIt = isolatedNodesSet.find(nodeOpt.value());
  ...
```

`nodeOpt.value()` is called before verifying the optional has something in it.

This should be updated to something like this:
```
template <typename T>
void Graph<T>::removeNode(const std::string &nodeUserId) {
  auto nodeOpt = getNode(nodeUserId);
  auto isolatedNodeIt = isolatedNodesSet.end();
  if (nodeOpt) {
    isolatedNodeIt  = isolatedNodeIt.find(nodeOpt.value());
  }
  ...
```

The tests should also be updated to test the case where we try to remove a node that does not exist in the graph.

**Comment by Ajay-26** [comment]
I would like to have a crack at this issue

**Comment by nolankramer** [comment]
@Ajay-26 Thanks! Go for it!

**Comment by Ajay-26** [comment]
Thank you for the quick reply @nolankramer! 
Quick question, for updating the tests, should I add a new test to [test/ConnectivityTest.cpp](https://github.com/ZigRazor/CXXGraph/blob/master/test/ConnectivityTest.cpp) or is there an existing test that it would be better for me to modify ? Also, if it would be better for the structure of the repo for me to add the test somewhere else, that would be just fine too :)

**Comment by Ajay-26** [comment]
Hi @nolankramer, I just made a PR from my branch to the head of the repo. I see that the CI test for Labeler / triage (pull_request_target) has failed, but I can't make much sense of the feedback from the test. I'm trying to fix that before I complete my PR, could you guide me on how to do it ? I can retract this PR and work on those changes.

**Comment by nolankramer** [comment]
@Ajay-26 No need to retract the PR. It seems like an unrelated issue. Feel free to ignore it.

**Comment by nolankramer** [comment]
I've added some feedback on the PR to point you in the right direction :)
