### ISSUE TITLE
this library is MPLv2,why the node_decl.h licence is AGPL?

### ISSUE THREAD

**Issue by wuauigstuangsuo** [ZigRazor/CXXGraph#471]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nolankramer** [comment]
This is vestigial of the transition from AGPL to MPL.

The library is MPL, and this comment will be stripped from files mentioning AGPL

**Comment by ZigRazor** [comment]
Closed by #472
