### ISSUE TITLE
Graph Slicing based on connectivity

### ISSUE THREAD

**Issue by ZigRazor** [ZigRazor/CXXGraph#53]
Add graph slicing based on connectivity. 
E.g. given
A -> B -> C <- D
A -> E -> C -> F
and the starting node A: A, B, and E can be sliced off.
Mathematical definition of the problem:
Let G be the set of nodes in a graph and n be a given node in that set. Let C be the non-strict subset of G containing both n and all nodes reachable from n, and let C' be its complement. There's a third set M, which is the non-strict subset of C containing all nodes that are reachable from any node in C'.
The problem consists of finding all nodes that belong to C but not to M.

The reason why this problem is relevant is because it's used in garbage collection systems to decide which other objects need to be released, given that one object is about to be released.

**Comment by sidml** [comment]
@ZigRazor 
I can work on this if it's okay. I was wondering if there is any specific algorithm for this or an optimized way of doing this ?
I was thinking of doing the following:
- Use DFS or BFS to find all nodes reachable from n. These are elements of set C.
- Initialize C' to be complement of C (i.e. all nodes - nodes that are in C)
- For all nodes in C', apply DFS/BFS and get the list of reachable nodes. This is set M.
- Finally removes nodes from C that belong to M. This is our solution.

**Comment by sidml** [comment]
@ZigRazor Thanks! I hope to keep working on new functionalities.
