### ISSUE TITLE
Add Tests on DFS Algorithms

### ISSUE THREAD

**Issue by ZigRazor** [ZigRazor/CXXGraph#58]
There is the necessity to write more test on DFS Algorithm.
Specialy on limit case.
Any contribution is appreciated.

**Comment by ErikDervishi03** [comment]
i created a new pull request #375.If this test is ok, i can write some other tests if needed. 
@ZigRazor

**Comment by ZigRazor** [comment]
@ErikDervishi03 good job!
Adding tests is always a good idea, so if you want, and you have time, you can add all the tests you want.
Obviously more the tests covers different branch of a function or code in general more the library is bug free.
So if possible try to test the so called "limit case". 
Another good task is mentioned in the #3 , also write some simple or more complex example is useful.
Thank you in Advance!

**Comment by ZigRazor** [comment]
After this, I Close this issue
