### ISSUE TITLE
Introduce Tests for Thread-Safe Bellman-Ford algorithm 

### ISSUE THREAD

**Issue by ZigRazor** [ZigRazor/CXXGraph#75]
Here we need tests for Thread-Safe Bellman-Ford Algorithm

**Comment by sidml** [comment]
@ZigRazor 
I don't see any test for thread safe version of dijkstra in the [test file](https://github.com/ZigRazor/CXXGraph/blob/master/test/DijkstraTest.cpp). It will be nice if you could provide reference for this test.

**Comment by ZigRazor** [comment]
@sidml yes, there is no test for this, it would be nice to add and test also dijkstra, but it should work!

**Comment by sidml** [comment]
When I try replacing `CXXGRAPH::Graph` with `CXXGRAPH::Graph_TS` in the existing tests, everything freezes. In the debugger, I saw that it was stuck at `getNodeSet`, so I concluded that there was some problem in acquiring locks.
Does  TS dijkstra work for you ? 
(I hope I am not doing something stupid :smile: )

**Comment by ZigRazor** [comment]
Probably not, it seems a deadlock, can you open an issue for this and resolve it? 
(I think just need to call the `Graph::Dijkstra()` instead of `Graph_TS::Dijkstra()` maybe also in the `getNodeSet()` etc. etc. )
