### ISSUE TITLE
__NODE_H__ header guard can create conflict

### ISSUE THREAD

**Issue by ZigRazor** [ZigRazor/CXXGraph#84]
you may want to put lib name into the guard (CXXGRAPH_NODE_H), or you'll conflict with all of these [guys](https://github.com/search?q=__NODE_H__&type=code)

**Comment by AlfredCP** [comment]
Hi ZigRazor, I would like to contribute in your project.
I am new on this contributing process so I would like to start with this easy one to get used to the procedure to fork -> clone -> commit -> push -> PR

**Comment by ZigRazor** [comment]
Welcome @AlfredCP 
Ok, I assign it to you. You can start correct it!

**Comment by AlfredCP** [comment]
Shall I modify only NODE header, as the ticket title/description says, or should we change them all (the ones that does not include the library name)?
Like __READER_H__,  __CONSTVALUE_H__  ...

**Comment by ZigRazor** [comment]
If you want, you can change all
